Traceback (most recent call last):
  File "/Users/macbook/opt/anaconda3/envs/stat/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/macbook/opt/anaconda3/envs/stat/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/macbook/opt/anaconda3/envs/stat/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/macbook/opt/anaconda3/envs/stat/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/macbook/opt/anaconda3/envs/stat/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/macbook/opt/anaconda3/envs/stat/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/macbook/opt/anaconda3/envs/stat/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# convert value to factors (readable)
dat_fact_online <- as_label(dat_online) %>% as_factor()
head(dat_fact_online,2)
------------------


[1m[33mError[39m:[22m
[1m[22m[33m![39m [90m[conflicted][39m [1mas_factor[22m found in 2 packages.
Either pick the one you want with `::`:
[36mâ€¢[39m [34msjlabelled[39m::as_factor
[36mâ€¢[39m [34mforcats[39m::as_factor
Or declare a preference with `conflicts_prefer()`:
[36mâ€¢[39m `conflicts_prefer(sjlabelled::as_factor)`
[36mâ€¢[39m `conflicts_prefer(forcats::as_factor)`
Traceback:

1. (function (value) 
 . {
 .     if (from_save(sys.calls())) 
 .         return(NULL)
 .     bt_name <- backtick(name)
 .     namespace <- map_chr(pkgs, function(pkg) {
 .         style_object(pkg, name)
 .     })
 .     names(namespace) <- rep("*", length(namespace))
 .     prefer <- prefer_bullets(pkgs, name)
 .     cli::cli_abort(c("{label_conflicted()} {.strong {name}} found in {length(pkgs)} packages.", 
 .         "Either pick the one you want with {.code ::}:", namespace, 
 .         "Or declare a preference with {.fn {add_ns('conflicts_prefer')}}:", 
 .         prefer))
 . })()
2. cli::cli_abort(c("{label_conflicted()} {.strong {name}} found in {length(pkgs)} packages.", 
 .     "Either pick the one you want with {.code ::}:", namespace, 
 .     "Or declare a preference with {.fn {add_ns('conflicts_prefer')}}:", 
 .     prefer))
3. rlang::abort(message, ..., call = call, use_cli_format = TRUE, 
 .     .frame = .frame)
4. signal_abort(cnd, .file)
5. signalCondition(cnd)

